# get all books
GET http://localhost:8080/books

###

# get book by id
GET http://localhost:8080/books/3





###
# add book

POST http://localhost:8080/books
Content-Type: application/json

{
    "name":"doremon",
    "id":"3"
}

###
# update a book by id
PATCH http://localhost:8080/books/3
Content-Type: application/json

{
    "name":"ben 10 classic"
}
###
# Delete a book by id

DELETE http://localhost:8080/books/3